command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "vj-database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: MASSIVE_API_BASE_URL
    value: "https://api.massive.com"
  - name: MASSIVE_SECRET_SCOPE
    value: "vj-massive"
  - name: MASSIVE_SECRET_KEY
    value: "api-key"
